require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VpcsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Vpc. As you add validations to Vpc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VpcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all vpcs as @vpcs" do
      vpc = Vpc.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:vpcs)).to eq([vpc])
    end
  end

  describe "GET #show" do
    it "assigns the requested vpc as @vpc" do
      vpc = Vpc.create! valid_attributes
      get :show, {:id => vpc.to_param}, valid_session
      expect(assigns(:vpc)).to eq(vpc)
    end
  end

  describe "GET #new" do
    it "assigns a new vpc as @vpc" do
      get :new, {}, valid_session
      expect(assigns(:vpc)).to be_a_new(Vpc)
    end
  end

  describe "GET #edit" do
    it "assigns the requested vpc as @vpc" do
      vpc = Vpc.create! valid_attributes
      get :edit, {:id => vpc.to_param}, valid_session
      expect(assigns(:vpc)).to eq(vpc)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Vpc" do
        expect {
          post :create, {:vpc => valid_attributes}, valid_session
        }.to change(Vpc, :count).by(1)
      end

      it "assigns a newly created vpc as @vpc" do
        post :create, {:vpc => valid_attributes}, valid_session
        expect(assigns(:vpc)).to be_a(Vpc)
        expect(assigns(:vpc)).to be_persisted
      end

      it "redirects to the created vpc" do
        post :create, {:vpc => valid_attributes}, valid_session
        expect(response).to redirect_to(Vpc.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved vpc as @vpc" do
        post :create, {:vpc => invalid_attributes}, valid_session
        expect(assigns(:vpc)).to be_a_new(Vpc)
      end

      it "re-renders the 'new' template" do
        post :create, {:vpc => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vpc" do
        vpc = Vpc.create! valid_attributes
        put :update, {:id => vpc.to_param, :vpc => new_attributes}, valid_session
        vpc.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested vpc as @vpc" do
        vpc = Vpc.create! valid_attributes
        put :update, {:id => vpc.to_param, :vpc => valid_attributes}, valid_session
        expect(assigns(:vpc)).to eq(vpc)
      end

      it "redirects to the vpc" do
        vpc = Vpc.create! valid_attributes
        put :update, {:id => vpc.to_param, :vpc => valid_attributes}, valid_session
        expect(response).to redirect_to(vpc)
      end
    end

    context "with invalid params" do
      it "assigns the vpc as @vpc" do
        vpc = Vpc.create! valid_attributes
        put :update, {:id => vpc.to_param, :vpc => invalid_attributes}, valid_session
        expect(assigns(:vpc)).to eq(vpc)
      end

      it "re-renders the 'edit' template" do
        vpc = Vpc.create! valid_attributes
        put :update, {:id => vpc.to_param, :vpc => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested vpc" do
      vpc = Vpc.create! valid_attributes
      expect {
        delete :destroy, {:id => vpc.to_param}, valid_session
      }.to change(Vpc, :count).by(-1)
    end

    it "redirects to the vpcs list" do
      vpc = Vpc.create! valid_attributes
      delete :destroy, {:id => vpc.to_param}, valid_session
      expect(response).to redirect_to(vpcs_url)
    end
  end

end
